//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nail_in_nottingham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDesk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillDesk()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int ID { get; set; }
        public int ServiceBilldeskId { get; set; }
        public int ServiceID { get; set; }
        public int ServiceDurationId { get; set; }
        public string ServiceTotalAmount { get; set; }
        public int NoOfPerson { get; set; }
    
        public virtual ServiceBillDesk ServiceBillDesk { get; set; }
        public virtual ServiceDuration ServiceDuration { get; set; }
        public virtual ServiceMaster ServiceMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
    }
}
