//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nail_in_nottingham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public string consumer_first_name { get; set; }
        public string consumer_last_name { get; set; }
        public string consumer__mobileno { get; set; }
        public string consumer_email { get; set; }
        public int service_id { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
