//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nail_in_nottingham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBillDesk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceBillDesk()
        {
            this.BillDesks = new HashSet<BillDesk>();
        }
    
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int ServiceDurationID { get; set; }
        public int ServicePriceID { get; set; }
        public int ServiceVeriationID { get; set; }
        public string ServiceAmount { get; set; }
        public int ServiceQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDesk> BillDesks { get; set; }
        public virtual ServiceMaster ServiceMaster { get; set; }
        public virtual ServiceDuration ServiceDuration { get; set; }
        public virtual ServicePrice ServicePrice { get; set; }
        public virtual ServiceVeriation ServiceVeriation { get; set; }
    }
}
