//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nail_in_nottingham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor
    {
        public int vstr_id { get; set; }
        public string visitor_name { get; set; }
        public string visitor_location { get; set; }
        public string visitor_phoneno { get; set; }
        public string visitor_email { get; set; }
        public string testimonials { get; set; }
        public string enquiry { get; set; }
    }
}
